version: "3.7"
services:
    gender-guessing-service:
        build: .
        ports:
          - "5000:5000"
        networks:
          seco:
            ipv4_address: "172.30.20.79"
        env_file:
          - docker.env
    henko-fuseki:
        build: https://version.aalto.fi/gitlab/seco/suomen-henkilonimisto.git
        networks:
          seco:
            ipv4_address: "172.30.20.81"

networks:
    seco:
      driver: "bridge"
      ipam:
        driver: "default"
        config:
          - subnet: "172.30.20.0/22"